Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('foods/', include('foods.urls')),
    path('', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('category/<slug:slug>', views.categoryDetail, name='category_detail'),
    path('detail/<slug:slug>', views.articleDetail, name='article_detail'),
    path('', views.ArticleList.as_view(), name='article_list'),
    path('search/', views.searchDetail, name='search')
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=155)
    slug = models.SlugField(unique=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.name)
        super(Category, self).save()

    def get_absolute_url(self):
        return reverse('blog:category_detail', kwargs={'slug': self.slug})


class Tag(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateField(auto_now_add=True)
    publish = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category, related_name='articles')
    tag = models.ManyToManyField(Tag, related_name='articles')
    body = models.TextField()
    slug = models.SlugField(unique=True, blank=True)
    image = models.ImageField(upload_to='image/article')
    image_for_detail = models.ImageField(upload_to='image/article_detail', default='inner-blog-img.jpg')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)
    view = models.IntegerField(default=0)
    class Meta:
        ordering = ('-created',)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.title)
        super(Article, self).save()

    def get_absolute_url(self):
        return reverse('blog:article_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.title} - {self.body[:30]}'


class Comment(models.Model):
    article = models.ForeignKey(Article, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:35]}'

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from .models import Article, Category, Comment
from django.core.paginator import Paginator
from .forms import CommentForm


class ArticleList(ListView):
    queryset = Article.objects.filter(status=True)
    template_name = 'blog/article_list.html'
    paginate_by = 2


def articleDetail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    article_view_sort = Article.objects.order_by('-view')
    category = Category.objects.all()
    # for the view increase
    article.view += 1
    article.save()

    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        if form.is_valid():
            body = form.cleaned_data.get('body')
            parent_id = request.POST.get('parent_id')
            Comment.objects.create(parent_id=parent_id, user=request.user, article=article, body=body)

    else:
        form = CommentForm()
    context = {
        'article': article,
        'category': category,
        'article_view_sort': article_view_sort,
        'form': form,
    }
    return render(request, 'blog/article_detail.html', context)


def categoryDetail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    object_list = category.articles.all()
    paginator = Paginator(object_list, 2)
    page_number = request.GET.get('page')
    object_list = paginator.get_page(page_number)
    return render(request, 'blog/article_list.html', context={'object_list': object_list})


def searchDetail(request):
    search = request.GET.get('search')
    object_list = Article.objects.filter(title__icontains=search)
    paginator = Paginator(object_list, 2)
    page_number = request.GET.get('page')
    object_list = paginator.get_page(page_number)
    return render(request, 'blog/article_list.html', context={'object_list': object_list})

# class ArticleDetail(DetailView):
#     queryset = Category.objects.all()
#     def get_object(self):
#         queryset = Category.objects.all()
#         slug = self.kwargs.get('slug')
#         return get_object_or_404(Article.objects.filter(status=True), slug=slug) ,queryset


# class CategoryDetail(DetailView):
#     def get_queryset(self):
#         slug = self.kwargs.get('slug')
#         return get_object_or_404(Category.objects.filter(status=True, slug=slug))

blog/templates/blog/article_detail.html
{% extends 'base.html' %}
{% load static %}
<!-- Start All Pages -->
{% block body %}
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>Blog</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->

<!-- Start blog details -->
<div class="blog-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>Blog</h2>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-8 col-lg-8 col-12">
                <div class="blog-inner-details-page">
                    <div class="blog-inner-box">
                        <div class="side-blog-img">
                            <img class="img-fluid" src="{{ article.image_for_detail.url }}" alt="">
                            <div class="date-blog-up">
                                27 Fab
                            </div>
                        </div>
                        <div class="inner-blog-detail details-page">
                            <h3>{{ article.title }}</h3>
                            <ul>
                                <li><i class="zmdi zmdi-account"></i>Posted By : <span>{{ article.author }}</span>
                                </li>
                                <li>|</li>
                                <li><i class="zmdi zmdi-time"></i>Time : <span>{{ article.created }}</span></li>
                            </ul>
                            <p>{{ article.body }}</p>
                        </div>
                    </div>
                    <div class="blog-comment-box">
                        <!-- comments -->
                        <h3>Comments</h3>
                        {% for comment in article.comments.all %}
                            {% if comment.parent == None %}
                                <div class="comment-item">
                                    <div class="comment-item-left">
                                        <img src="{% static 'images/avt-img.jpg' %}" alt="">
                                    </div>
                                    <div class="comment-item-right">
                                        <div class="pull-left">
                                            <a href="#">{{ comment.user }}</a>
                                        </div>
                                        <div class="pull-right">
                                            <i class="fa fa-clock-o" aria-hidden="true"></i>Time :
                                            <span>{{ comment.created_at }}</span>
                                        </div>
                                        <div class="des-l">
                                            <p>{{ comment.body }}</p>
                                        </div>
                                        <a href="#" onclick="set_value({{ comment.id }})" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i>
                                            Reply</a>
                                    </div>
                                </div>
                                {% for reply in comment.replies.all %}
                                    <div class="comment-item children">
                                        <div class="comment-item-left">
                                            <img src="{% static 'images/avt-img.jpg' %}" alt="">
                                        </div>
                                        <div class="comment-item-right">
                                            <div class="pull-left">
                                                <a href="#">{{reply.user}}</a>
                                            </div>
                                            <div class="pull-right">
                                                <i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>{{ reply.created_at }}</span>
                                            </div>
                                            <div class="des-l">
                                                <p>{{ reply.body }}</p>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="comment-respond-box">
                        <h3>Leave your comment </h3>
                        <div class="comment-respond-form">
                            {% if request.user.is_authenticated %}
                                <form id="commentrespondform" class="comment-form-respond row" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="parent_id" id="parent_id" value="">
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <div class="form-group">
                                            {{ form }}
{#                                            <textarea class="form-control" id="body" name="body" placeholder="Your Message" rows="2"></textarea>#}
                                        </div>
                                    </div>  
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <button class="btn btn-submit">Submit comment</button>
                                    </div>
                                </form>
                                {% else %}
                                    <p class="btn btn-danger"><a href=""></a>for send comment please login</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
                <div class="right-side-blog">
                    <h3>Search</h3>
                    <form action="{% url 'blog:search' %}" method="get">
                        <div class="blog-search-form">
                            <input name="search" placeholder="Search blog" type="text">
                            <button class="search-btn">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </button>
                        </div>
                    </form>
                    
                    <h3>Categories</h3>
                    <div class="blog-categories">
                        <ul>
                            {% for cat in category|slice:":4" %}
                            <li><a href="{% url 'blog:category_detail' cat.slug %}"><span>{{ cat.name }}</span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <h3>Recent Post</h3>
                    <div class="post-box-blog">
                        <div class="recent-post-box">
                            {% for article in article_view_sort|slice:":3" %}
                                <div class="recent-box-blog">
                                    <div class="recent-img">
                                        <img style="width: 80px; height: 80px;" class="img-fluid" src="{{ article.image.url }}" alt="{{ article.title }}">
                                    </div>
                                    <div class="recent-info">
                                        <ul>
                                            <li><i class="zmdi zmdi-account"></i>Posted By : <span>{{ article.author }}</span>
                                            </li>
                                            <li>|</li>
                                            <li><i class="zmdi zmdi-time"></i>Time : <span>{{ article.created }}</span></li>
                                        </ul>
                                        <h4> {{article.body|truncatewords:5}} </h4>
                                    </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <h3>Recent Tag</h3>
                    <div class="blog-tag-box">
                        <ul class="list-inline tag-list">

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End details -->
<script>
    function set_value(id){
        document.getElementById('parent_id').value = id;
        window.location.href = '#body';
    }
</script>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <!-- Start All Pages -->
    <div class="all-page-title page-breadcrumb">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Blog</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Pages -->

    <!-- Start blog -->
    <div class="blog-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-title text-center">
                        <h2>Blog</h2>
                        <p>Welcome to Yamifood blog</p>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for article in object_list %}
                    <div class="col-lg-4 col-md-6 col-12">
                        <div class="blog-box-inner">
                            <div class="blog-img-box">
                                <img class="img-fluid" src="{{ article.image.url }}" alt="">
                            </div>
                            <div class="blog-detail">
                                <h4>{{ article.title }}</h4>
                                <ul>
                                    <li><span>Post by {{ article.author }}</span></li>
                                    <li>|</li>
                                    <li><span>{{ article.created }}</span></li>
                                </ul>
                                <p>{{ article.body|truncatechars:300 }}</p>
                                <a class="btn btn-lg btn-circle btn-outline-new-white"
                                   href="{{ article.get_absolute_url }}">Read More</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <!-- End blog -->

    </div>
    {#    {% if page_obj.has_otder_pages %}#}
    <nav class="d-flex justify-content-center mb-5" aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                </li>
            {% endif %}
            {% for page in page_obj.paginator.page_range %}
                {% if page_obj.number == page %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{ page }}">{{ page }}<span class="sr-only">(current)</span></a>
                    </li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    {#    {% endif %}#}
{% endblock %}